import { describe, expect, it } from "vitest";

import { GitLabHttpError, createGitLabClient } from "../../src/gitlab.js";

function jsonResponse(body: unknown, init: ResponseInit = {}): Response {
  const headers = new Headers(init.headers);
  headers.set("content-type", "application/json");
  return new Response(JSON.stringify(body), {
    status: init.status ?? 200,
    headers,
  });
}

describe("GitLab client", () => {
  it("fetches MR metadata and validates the response shape", async () => {
    const client = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async (url, init) => {
        if (typeof url !== "string") {
          throw new Error("Expected GitLab client to call fetch with a string URL");
        }
        expect(url).toBe(
          "https://gitlab.example.com/api/v4/projects/repo-a/merge_requests/123",
        );
        expect((init?.headers as Record<string, string>)["PRIVATE-TOKEN"]).toBe("token-1");
        return jsonResponse({
          iid: 123,
          title: "Fix bug",
          sha: "abc123",
          source_branch: "feature/fix",
          web_url: "https://gitlab.example.com/repo-a/-/merge_requests/123",
        });
      },
    });

    await expect(client.getMergeRequest("repo-a", 123)).resolves.toMatchObject({
      headSha: "abc123",
      iid: 123,
      sourceBranch: "feature/fix",
    });
  });

  it("fetches the current token user for MR assignment", async () => {
    const client = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async (url, init) => {
        expect(url).toBe("https://gitlab.example.com/api/v4/user");
        expect((init?.headers as Record<string, string>)["PRIVATE-TOKEN"]).toBe("token-1");
        return jsonResponse({ id: 42, username: "gitport-bot" });
      },
    });

    await expect(client.getCurrentUser()).resolves.toEqual({ id: 42, username: "gitport-bot" });
  });

  it("creates Draft MRs with draft=true, the provided title, and assignee", async () => {
    let body: unknown;
    const client = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async (_url, init) => {
        if (typeof init?.body !== "string") {
          throw new Error("Expected GitLab client to send a string JSON body");
        }
        body = JSON.parse(init.body) as unknown;
        return jsonResponse({
          iid: 7,
          web_url: "https://gitlab.example.com/repo-b/-/merge_requests/7",
          draft: true,
        });
      },
    });

    const result = await client.createDraftMergeRequest("repo-b", {
      sourceBranch: "gitport/repo-a-mr-123",
      targetBranch: "main",
      title: "JIR-112 align auth",
      description: "Generated by Gitport",
      assigneeId: 42,
    });

    expect(result.webUrl).toContain("/merge_requests/7");
    expect(body).toMatchObject({
      draft: true,
      source_branch: "gitport/repo-a-mr-123",
      target_branch: "main",
      title: "Draft: JIR-112 align auth",
      assignee_ids: [42],
    });
  });

  it("does not double-prefix titles that already start with Draft", async () => {
    let body: unknown;
    const client = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4/",
      token: "token-1",
      fetchFn: async (_url, init) => {
        if (typeof init?.body !== "string") {
          throw new Error("Expected JSON body");
        }
        body = JSON.parse(init.body) as unknown;
        return jsonResponse({
          iid: 7,
          web_url: "https://gitlab.example.com/repo-b/-/merge_requests/7",
        });
      },
    });

    await client.createDraftMergeRequest("repo-b", {
      sourceBranch: "p",
      targetBranch: "main",
      title: "Draft: Existing",
      description: "Generated by Gitport",
      assigneeId: 42,
    });

    expect(body).toMatchObject({ title: "Draft: Existing" });
  });

  it("lists MR commits and validates arrays", async () => {
    const client = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async () =>
        jsonResponse([{ id: "abc", title: "commit title", message: "commit title\n\nbody" }]),
    });

    await expect(client.listMergeRequestCommits("repo-a", 123)).resolves.toEqual([
      { sha: "abc", title: "commit title", message: "commit title\n\nbody" },
    ]);
  });

  it("follows GitLab pagination headers when listing MR commits", async () => {
    const requested: string[] = [];
    const client = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async (url) => {
        if (typeof url !== "string") {
          throw new Error("Expected string URL");
        }
        requested.push(url);
        const page = new URL(url).searchParams.get("page");
        if (page === "1") {
          return jsonResponse([{ id: "one", title: "one", message: "one" }], {
            headers: { "x-next-page": "2" },
          });
        }
        return jsonResponse([{ id: "two", title: "two", message: "two" }], {
          headers: { "x-next-page": "" },
        });
      },
    });

    await expect(client.listMergeRequestCommits("repo-a", 123)).resolves.toEqual([
      { sha: "one", title: "one", message: "one" },
      { sha: "two", title: "two", message: "two" },
    ]);
    expect(requested).toHaveLength(2);
    expect(requested[0]).toContain("page=1");
    expect(requested[1]).toContain("page=2");
  });

  it("falls back to the Link header for commit pagination", async () => {
    const client = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async (url) => {
        if (typeof url !== "string") {
          throw new Error("Expected string URL");
        }
        const page = new URL(url).searchParams.get("page");
        if (page === "1") {
          return jsonResponse([{ id: "one", title: "one", message: "one" }], {
            headers: {
              link: '<https://gitlab.example.com/api/v4/projects/repo-a/merge_requests/123/commits?page=2&per_page=100>; rel="next"',
            },
          });
        }
        return jsonResponse([{ id: "two", title: "two", message: "two" }]);
      },
    });

    await expect(client.listMergeRequestCommits("repo-a", 123)).resolves.toHaveLength(2);
  });

  it("rejects malformed GitLab responses", async () => {
    const mrClient = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async () => jsonResponse([]),
    });
    await expect(mrClient.getMergeRequest("repo-a", 123)).rejects.toThrow(/MR response/);

    const missingMrFieldClient = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async () => jsonResponse({ iid: 123, title: "MR" }),
    });
    await expect(missingMrFieldClient.getMergeRequest("repo-a", 123)).rejects.toThrow(
      /MR response is missing fields/,
    );

    const commitsClient = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async () => jsonResponse({ id: "abc" }),
    });
    await expect(commitsClient.listMergeRequestCommits("repo-a", 123)).rejects.toThrow(
      /commits response/,
    );

    const createdClient = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async () => jsonResponse({ iid: 1 }),
    });
    await expect(
      createdClient.createDraftMergeRequest("repo-b", {
        sourceBranch: "p",
        targetBranch: "main",
        title: "Draft",
        description: "body",
        assigneeId: 42,
      }),
    ).rejects.toThrow(/Created MR response/);

    const createdArrayClient = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async () => jsonResponse([]),
    });
    await expect(
      createdArrayClient.createDraftMergeRequest("repo-b", {
        sourceBranch: "p",
        targetBranch: "main",
        title: "Draft",
        description: "body",
        assigneeId: 42,
      }),
    ).rejects.toThrow(/Created MR response is not an object/);

    const userClient = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async () => jsonResponse({ username: "missing-id" }),
    });
    await expect(userClient.getCurrentUser()).rejects.toThrow(/Current user response/);
  });

  it("rejects malformed commit entries", async () => {
    const objectClient = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async () => jsonResponse([null]),
    });
    await expect(objectClient.listMergeRequestCommits("repo-a", 123)).rejects.toThrow(
      /commit response is not an object/,
    );

    const missingFieldClient = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "token-1",
      fetchFn: async () => jsonResponse([{ id: "abc" }]),
    });
    await expect(missingFieldClient.listMergeRequestCommits("repo-a", 123)).rejects.toThrow(
      /commit response is missing fields/,
    );
  });

  it("redacts token values from GitLab HTTP errors", async () => {
    const client = createGitLabClient({
      baseUrl: "https://gitlab.example.com/api/v4",
      token: "super-token",
      fetchFn: async () => jsonResponse({ message: "bad super-token" }, { status: 401 }),
    });

    await expect(client.getMergeRequest("repo-a", 1)).rejects.toThrow(GitLabHttpError);
    await expect(client.getMergeRequest("repo-a", 1)).rejects.not.toThrow(/super-token/);
  });
});
