export const DEFAULT_TUNNEL_READY_TIMEOUT_MS = 180_000;
export const POST_USR1_DELAY_MS = 300;
export const CHILD_SIGTERM_GRACE_MS = 2_000;
export const CHILD_SIGKILL_GRACE_MS = 1_000;
export const PID_TERMINATION_POLL_MS = 100;
